### ISSUE TITLE
Post/Get request returning None

### ISSUE THREAD

**Issue by Deepthi-Nacharaju** [Deepthi-Nacharaju/heart_rate_sentinel_server#2]
when I try to print(r.json()) it throws an error because it can't decode None. This makes me think the request isn't working altogether? If you run my main.py, it should do a post and a get request in the main method but right now it's not working ..... :(

**Comment by dward2** [comment]
I just tried the code on your master branch and it worked on my computer.   Can you be more specific about the error you are getting?  Can you post a screen shot or copy/paste the detailed error text?

**Comment by Deepthi-Nacharaju** [comment]
My bad for not clarifying, my issue is on the store_data branch I'm developing

**Comment by dward2** [comment]
I can start your server code successfully.  Then, when I run `main.py`, I also get an error related to the `print(r.json())` line of code.  That is because there was an error on the server and so the "r" variable doesn't contain any json information, rather the error code 500.  To determine the error on the server, I then look into the terminal window that is running the server code.  There I see error results with an error of
```
pymongo.errors.OperationFailure: Authentication failed.
```
related to line 23 `new_patient.save()`.  So, check your mongo interface and make sure you can successfully add to the database.
